name: lint

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - '**' # all tags
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install webp
        run : sudo apt-get install libwebp-dev

      - name: go lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.50.1
